#!/usr/bin/env bash
# Install the Monterey-compatible cua-driver build for Hermes Agent.
#
# Intended for macOS 12.7 / Monterey on the monterey-support-v1 branch.
# The script builds cua-driver from source, installs a stable local symlink,
# writes an environment helper for Hermes, and runs Hermes diagnostics when
# the `hermes` CLI is available.
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
DRIVER_ROOT="$(cd -- "$SCRIPT_DIR/.." && pwd)"
RUST_ROOT="$DRIVER_ROOT/rust"
INSTALL_DIR="${HOME}/.local/bin"
ENV_DIR="${HOME}/.hermes"
ENV_FILE="$ENV_DIR/cua-driver-monterey.env"
LINK_PATH="$INSTALL_DIR/cua-driver-monterey"

if [[ "$(uname -s)" != "Darwin" ]]; then
    echo "error: this installer is only for macOS" >&2
    exit 1
fi

MACOS_VERSION="$(sw_vers -productVersion 2>/dev/null || true)"
MACOS_MAJOR="${MACOS_VERSION%%.*}"
if [[ -z "$MACOS_VERSION" ]]; then
    echo "error: unable to determine macOS version" >&2
    exit 1
fi

if [[ "$MACOS_MAJOR" -lt 12 ]]; then
    echo "error: macOS $MACOS_VERSION is too old; Monterey (12.x) or newer is required" >&2
    exit 1
fi

if ! command -v cargo >/dev/null 2>&1; then
    echo "error: cargo was not found. Install Rust with rustup first." >&2
    exit 1
fi

if ! command -v xcrun >/dev/null 2>&1; then
    echo "error: Xcode Command Line Tools are required (xcode-select --install)" >&2
    exit 1
fi

mkdir -p "$INSTALL_DIR" "$ENV_DIR"

echo "==> Building Monterey cua-driver for Hermes"
cd "$RUST_ROOT"
MACOSX_DEPLOYMENT_TARGET=12.3 cargo build --release -p cua-driver

BIN="$RUST_ROOT/target/release/cua-driver"
if [[ ! -x "$BIN" ]]; then
    echo "error: build completed but cua-driver binary was not found at $BIN" >&2
    exit 1
fi

ln -sfn "$BIN" "$LINK_PATH"

cat > "$ENV_FILE" <<EOF
# Generated by install-hermes-monterey.sh
# Source this file before launching Hermes, or add the export to your shell rc.
export HERMES_CUA_DRIVER_CMD="$LINK_PATH"
export CUA_DRIVER_RS_TELEMETRY_ENABLED=0
EOF

# Add a small shell snippet once. Hermes launched from a terminal will then use
# the Monterey driver automatically. We intentionally do not edit Hermes'
# config.yaml because HERMES_CUA_DRIVER_CMD is the supported local-build hook.
SHELL_RC="${HOME}/.zshrc"
if [[ -n "${BASH_VERSION:-}" && "${SHELL##*/}" == "bash" ]]; then
    SHELL_RC="${HOME}/.bash_profile"
fi
MARKER="# cua-driver Monterey for Hermes"
if ! grep -Fq "$MARKER" "$SHELL_RC" 2>/dev/null; then
    {
        echo ""
        echo "$MARKER"
        echo "[ -f \"$ENV_FILE\" ] && source \"$ENV_FILE\""
    } >> "$SHELL_RC"
fi

export HERMES_CUA_DRIVER_CMD="$LINK_PATH"
export CUA_DRIVER_RS_TELEMETRY_ENABLED=0

echo "==> Installed: $LINK_PATH"
echo "==> Hermes env: $ENV_FILE"
echo "==> Driver version:"
"$LINK_PATH" --version || true

if command -v hermes >/dev/null 2>&1; then
    echo "==> Hermes computer-use status"
    hermes computer-use status || true
    echo "==> Hermes computer-use doctor"
    hermes computer-use doctor || true
else
    echo "note: Hermes CLI was not found in PATH."
    echo "After Hermes is available, run:"
    echo "  source \"$ENV_FILE\""
    echo "  hermes computer-use status"
    echo "  hermes computer-use doctor"
fi

echo ""
echo "Installation complete."
echo "Open a new terminal, then run: hermes -t computer_use chat"
echo "On macOS, grant the identity reported by 'hermes computer-use doctor'"
echo "Accessibility and Screen Recording permissions in System Settings."
