#!/usr/bin/env bash
# Install the Monterey-compatible cua-driver build for Hermes Agent.
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
DRIVER_ROOT="$(cd -- "$SCRIPT_DIR/.." && pwd)"
RUST_ROOT="$DRIVER_ROOT/rust"
INSTALL_DIR="${HOME}/.local/bin"
ENV_DIR="${HOME}/.hermes"
ENV_FILE="$ENV_DIR/cua-driver-monterey.env"
LINK_PATH="$INSTALL_DIR/cua-driver-monterey"
STANDARD_LINK_PATH="$INSTALL_DIR/cua-driver"
REALPATH_SHIM="$INSTALL_DIR/realpath"
LINKER_WRAPPER="$RUST_ROOT/scripts/clang-monterey-linker.sh"
APP_ROOT="${HOME}/Applications/CuaDriver.app"
APP_CONTENTS="$APP_ROOT/Contents"
APP_MACOS="$APP_CONTENTS/MacOS"
APP_BIN="$APP_MACOS/cua-driver"

if [[ "$(uname -s)" != "Darwin" ]]; then
    echo "error: this installer is only for macOS" >&2
    exit 1
fi

MACOS_VERSION="$(sw_vers -productVersion 2>/dev/null || true)"
MACOS_MAJOR="${MACOS_VERSION%%.*}"
if [[ -z "$MACOS_VERSION" ]]; then
    echo "error: unable to determine macOS version" >&2
    exit 1
fi
if [[ "$MACOS_MAJOR" -lt 12 ]]; then
    echo "error: macOS $MACOS_VERSION is too old; Monterey (12.x) or newer is required" >&2
    exit 1
fi

command -v cargo >/dev/null 2>&1 || { echo "error: cargo was not found" >&2; exit 1; }
command -v xcrun >/dev/null 2>&1 || { echo "error: Xcode Command Line Tools are required" >&2; exit 1; }
[[ -f "$LINKER_WRAPPER" ]] || { echo "error: Monterey linker wrapper missing" >&2; exit 1; }
chmod +x "$LINKER_WRAPPER"

mkdir -p "$INSTALL_DIR" "$ENV_DIR" "$HOME/Applications"

# Monterey does not always provide a `realpath` command. Hermes/browser-use
# startup helpers may assume it exists, so install a tiny compatible fallback
# only when no realpath is already available.
if ! command -v realpath >/dev/null 2>&1; then
    cat > "$REALPATH_SHIM" <<'PY'
#!/usr/bin/env python3
import os
import sys

if len(sys.argv) < 2:
    print("realpath: missing operand", file=sys.stderr)
    sys.exit(1)

for path in sys.argv[1:]:
    print(os.path.realpath(path))
PY
    chmod +x "$REALPATH_SHIM"
    echo "==> Installed Monterey realpath compatibility shim: $REALPATH_SHIM"
fi

export PATH="$INSTALL_DIR:$PATH"

echo "==> Building Monterey cua-driver for Hermes"
cd "$RUST_ROOT"
MACOSX_DEPLOYMENT_TARGET=12.3 \
CARGO_TARGET_X86_64_APPLE_DARWIN_LINKER="$LINKER_WRAPPER" \
cargo build --release -p cua-driver

BIN="$RUST_ROOT/target/release/cua-driver"
[[ -x "$BIN" ]] || { echo "error: cua-driver binary not found at $BIN" >&2; exit 1; }

ln -sfn "$BIN" "$LINK_PATH"
ln -sfn "$BIN" "$STANDARD_LINK_PATH"

rm -rf "$APP_ROOT"
mkdir -p "$APP_MACOS"
cp "$BIN" "$APP_BIN"
chmod +x "$APP_BIN"
cat > "$APP_CONTENTS/Info.plist" <<'PLIST'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key><string>CuaDriver</string>
  <key>CFBundleDisplayName</key><string>CuaDriver</string>
  <key>CFBundleExecutable</key><string>cua-driver</string>
  <key>CFBundleIdentifier</key><string>com.trycua.driver</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleShortVersionString</key><string>0.25.0</string>
  <key>CFBundleVersion</key><string>25</string>
  <key>LSBackgroundOnly</key><true/>
  <key>NSHighResolutionCapable</key><true/>
</dict>
</plist>
PLIST

if command -v codesign >/dev/null 2>&1; then
    codesign --force --deep --sign - "$APP_ROOT" >/dev/null 2>&1 || true
fi

LSREGISTER="/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister"
if [[ -x "$LSREGISTER" ]]; then
    "$LSREGISTER" -f "$APP_ROOT" >/dev/null 2>&1 || true
fi

cat > "$ENV_FILE" <<EOF
# Generated by install-hermes-monterey.sh
export PATH="$INSTALL_DIR:\$PATH"
export HERMES_CUA_DRIVER_CMD="$LINK_PATH"
export CUA_DRIVER_RS_TELEMETRY_ENABLED=0
EOF

SHELL_RC="${HOME}/.zshrc"
if [[ -n "${BASH_VERSION:-}" && "${SHELL##*/}" == "bash" ]]; then
    SHELL_RC="${HOME}/.bash_profile"
fi
MARKER="# cua-driver Monterey for Hermes"
if ! grep -Fq "$MARKER" "$SHELL_RC" 2>/dev/null; then
    {
        echo ""
        echo "$MARKER"
        echo "[ -f \"$ENV_FILE\" ] && source \"$ENV_FILE\""
    } >> "$SHELL_RC"
fi

export HERMES_CUA_DRIVER_CMD="$LINK_PATH"
export CUA_DRIVER_RS_TELEMETRY_ENABLED=0

echo "==> Installed binary: $LINK_PATH"
echo "==> Standard PATH link: $STANDARD_LINK_PATH"
echo "==> Installed app: $APP_ROOT"
echo "==> Hermes env: $ENV_FILE"
"$LINK_PATH" --version || true

open -n -g -a CuaDriver --args serve >/dev/null 2>&1 || true
sleep 2

if command -v browser-use >/dev/null 2>&1; then
    echo "==> Browser Use detected: $(command -v browser-use)"
    browser-use --help >/dev/null 2>&1 && echo "==> Browser Use CLI: ok" || echo "warning: browser-use exists but failed its --help check"
else
    echo "note: browser-use CLI was not found in PATH; realpath compatibility is ready if/when it is installed."
fi

if command -v hermes >/dev/null 2>&1; then
    echo "==> Hermes computer-use status"
    hermes computer-use status || true
    echo "==> Hermes computer-use doctor"
    hermes computer-use doctor || true
else
    echo "note: Hermes CLI was not found in PATH."
fi

echo ""
echo "Installation complete."
echo "If doctor reports missing permissions, grant CuaDriver under:"
echo "  System Preferences > Security & Privacy > Privacy > Accessibility"
echo "  System Preferences > Security & Privacy > Privacy > Screen Recording"
echo "Then quit/relaunch CuaDriver or log out/in if Monterey asks for it."
echo "After that run: hermes computer-use doctor"
